const state = (result) => ({ status: result?.status || 'empty', message: result?.message || 'Nenhum registro disponível.' });
const payload = (result) => result?.status === 'success' && result.data && typeof result.data === 'object' ? result.data : {};
const list = (value) => Array.isArray(value) ? value : [];
const text = (value, fallback = '') => typeof value === 'string' ? value : fallback;

export const DashboardDTO = {
  fromResult: (result) => {
    const data = payload(result);
    return {
      header: { environmentLabel: text(data.header?.environmentLabel, 'Workspace autenticado'), footerNote: text(data.header?.footerNote, 'Dados protegidos por contexto autorizado.') },
      hero: { eyebrow: text(data.hero?.eyebrow, 'Portal do Investidor'), title: text(data.hero?.title, 'Dashboard'), description: text(data.hero?.description, 'Nenhum dado publicado.'), highlights: list(data.hero?.highlights) },
      projectStatus: list(data.projectStatus), roadmap: list(data.roadmap),
      evolution: { title: text(data.evolution?.title, 'Evolução do Projeto'), description: text(data.evolution?.description), labels: list(data.evolution?.labels), values: list(data.evolution?.values) },
      nextSteps: list(data.nextSteps), sidebar: list(data.sidebar), moduleState: state(result)
    };
  }
};

export const UpdatesDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Comunicação oficial'), title: text(data.page?.title, 'Atualizações Oficiais'), description: text(data.page?.description, 'Nenhuma atualização publicada.') }, categories: list(data.categories), statuses: list(data.statuses), updates: list(data.updates), moduleState: state(result) }; } };
export const DocumentsDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Investor Data Room'), title: text(data.page?.title, 'Documentos do Investidor'), description: text(data.page?.description, 'Nenhum documento publicado.') }, dashboard: { title: text(data.dashboard?.title, 'Documentos Recentes'), description: text(data.dashboard?.description, 'Nenhum documento disponível.') }, categories: list(data.categories), statuses: list(data.statuses), documents: list(data.documents), moduleState: state(result) }; } };
export const RoadmapDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Roadmap'), title: text(data.page?.title, 'Roadmap do REROUTE'), description: text(data.page?.description, 'Nenhum marco publicado.') }, dashboard: { title: text(data.dashboard?.title, 'Roadmap Geral'), description: text(data.dashboard?.description, 'Nenhum marco disponível.') }, categories: list(data.categories), statuses: list(data.statuses), statusOrder: list(data.statusOrder), milestones: list(data.milestones), summary: data.summary || { total: 0, completed: 0, inProgress: 0, planned: 0, progress: 0, currentSprint: 'Sem registro', nextSprint: 'Sem registro', latestUpdate: null }, moduleState: state(result) }; } };
export const ProjectsDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Execution Center'), title: text(data.page?.title, 'MVP / Projetos'), description: text(data.page?.description, 'Nenhum projeto publicado.') }, dashboard: { title: text(data.dashboard?.title, 'Execution Center'), description: text(data.dashboard?.description, 'Nenhum projeto disponível.') }, statuses: list(data.statuses), categories: list(data.categories), priorities: list(data.priorities), projects: list(data.projects), epics: list(data.epics), modules: list(data.modules), sprints: list(data.sprints), tasks: list(data.tasks), summary: data.summary || { projects: 0, epics: 0, modules: 0, sprints: 0, tasks: 0, progress: 0, activeProjects: 0, currentSprint: 'Sem registro', completedTasks: 0, upcomingDeliveries: [] }, moduleState: state(result) }; } };
export const InvestorsDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Gestão de Investidores'), title: text(data.page?.title, 'Investidores e Cap Table'), description: text(data.page?.description, 'Nenhum investidor disponível.') }, dashboard: { title: text(data.dashboard?.title, 'Cap Table'), description: text(data.dashboard?.description, 'Nenhuma posição disponível.') }, quotaValue: Number(data.quotaValue || 0), totalQuotas: Number(data.totalQuotas || 0), statuses: data.statuses || { investment: [], payment: [], documentation: [], access: [], labels: {} }, investors: list(data.investors), capTable: list(data.capTable), contributions: list(data.contributions), documents: list(data.documents), summary: data.summary || { committedCapital: 0, paidCapital: 0, pendingCapital: 0, occupiedQuotas: 0, availableQuotas: 0, distributedOwnership: 0 }, alerts: list(data.alerts), charts: data.charts || { capital: { labels: [], values: [] }, ownership: { labels: [], values: [] }, occupancy: { labels: [], values: [] }, contributions: { labels: [], values: [] } }, moduleState: state(result) }; } };
export const AdminDTO = { fromResult: (result) => { const data = payload(result); return { page: { eyebrow: text(data.page?.eyebrow, 'Governança'), title: text(data.page?.title, 'Admin Center'), description: text(data.page?.description, 'Nenhum dado administrativo disponível.') }, navigation: list(data.navigation), metrics: list(data.metrics), workspaces: list(data.workspaces), roles: list(data.roles), capabilities: list(data.capabilities), users: list(data.users), invites: list(data.invites), editorial: list(data.editorial), roadmapAdmin: list(data.roadmapAdmin), documentsAdmin: list(data.documentsAdmin), settings: list(data.settings), logs: list(data.logs), audit: list(data.audit), moduleState: state(result) }; } };

